sources:
    - name: bronze
      database: '{{ target.catalog }}'
      schema: bronze
      tables:
        - name: customers
        - name: order_items
        - name: orders
        - name: payments
        - name: products
        - name: reviews

